pages:
  image: docker.io/jangorecki/r-pkg
  script:
    # install suggested deps
    - Rscript -e 'install.packages(c("knitr","git2r"))'
    # build pkg
    - R CMD build .
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
    # produce artifacts
    - R CMD INSTALL $(ls -1t *.tar.gz | head -n 1) # use latest drat@artifacts to populate artifacts
    - Rscript -e 'drat::insertArtifacts(repodir="public", repo.url="https://jangorecki.gitlab.io/drat", log.files="tests/simpleTests.Rout")'
  only:
    - artifacts
  artifacts:
    paths:
      - public
