pages:
  image: docker.io/jangorecki/r-pkg
  script:
    # install suggested deps - knitr already in r-pkg image
    - Rscript -e 'install.packages("git2r")'
    # build pkg
    - R CMD build .
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
    # produce artifacts
    - R CMD INSTALL $(ls -1t *.tar.gz | head -n 1) # remove when new drat@artifacts deployed to r-pkg
    - Rscript -e 'drat::insertArtifacts(repodir="public", repo.url="https://jangorecki.gitlab.io/drat", log.files="tests/simpleTests.Rout")'
  only:
    - artifacts
  artifacts:
    paths:
      - public
